name: github action 테스트

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps: 
        # 소스코드를 window에 복사
        - name: 소스코드를 window 에 복사
          uses: actions/checkout@v2
        # window 에 python 개발환경 구축
        - name: window 에 python 개발환경 구축
          uses: actions/setup-python@v2
          with: 
            python-version: '3.10'
        # python main.py 명령어 실행
        - name: python main.py 실행
          run: python main.py